from python:3.11-alpine

# Set working directory
WORKDIR /usr/src/app

# Install Doppler CLI
RUN wget -q -t3 'https://packages.doppler.com/public/cli/rsa.8004D9FF50437357.key' -O /etc/apk/keys/cli@doppler-8004D9FF50437357.rsa.pub && \
    echo 'https://packages.doppler.com/public/cli/alpine/any-version/main' | tee -a /etc/apk/repositories && \
    apk add doppler

# Install dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Create database directory
RUN mkdir -p /usr/src/app/database

# Copy app
COPY . .

# Download config from Doppler
ENTRYPOINT ["doppler", "run", "--"]
# Run app
CMD [ "python", "main.py" ]